securitySettings:
  clientTlsPolicy: projects/meshca-gke-test/locations/global/clientTlsPolicies/client_mtls_policy
  subjectAltNames:
    - "spiffe://meshca-gke-test.svc.id.goog/ns/default/sa/example-grpc-server"
