apiVersion: security.cloud.google.com/v1alpha1
kind: TrustConfig
metadata:
  name: default
spec:
  # You must include a trustStores entry for the trust domain that
  # your cluster is enrolled in.
  trustStores:
  - trustDomain: meshca-gke-test.svc.id.goog
    # Trust identities in this trustDomain if they appear in a certificate
    # that chains up to this root CA.
    trustAnchors:
    - certificateAuthorityServiceURI: //privateca.googleapis.com/projects/meshca-gke-test/locations/us-west1/certificateAuthorities/zatar-root-apr21
