apiVersion: security.cloud.google.com/v1alpha1
kind: TrustConfig
metadata:
  name: default
spec:
  # You must include a trustStores entry for the trust domain that
  # your cluster is enrolled in.
  trustStores:
  - trustDomain: sanjaypujare-2-gke-dev.svc.id.goog
    # Trust identities in this trustDomain if they appear in a certificate
    # that chains up to this root CA.
    trustAnchors:
    - certificateAuthorityServiceURI: //privateca.googleapis.com/projects/sanjaypujare-2-gke-dev/locations/us-west1/certificateAuthorities/gke_pp_subordinate_ca
