FROM openjdk:10

ADD bootstrap-server.json /bootstrap-server.json

ADD sds-testing/logging.properties /logging.properties

RUN mkdir -p /build/install/example-tls

ADD build/install/example-tls /build/install/example-tls

ENV GRPC_XDS_BOOTSTRAP=/bootstrap-server.json

ENV JAVA_OPTS="-Djava.util.logging.config.file=/logging.properties"

#CMD ["/build/install/example-tls/bin/hello-world-tls-server","0.0.0.0","8000"]

EXPOSE 8000
