FROM openjdk:8

ADD istioClientScript.sh /istioClientScript.sh

RUN mkdir -p /build/install/example-tls

ADD build/install/example-tls /build/install/example-tls

CMD ["/bin/sh","-c","/istioClientScript.sh"]
