FROM openjdk:8

ADD clientScript.sh /clientScript.sh

RUN mkdir -p /build/install/example-tls

ADD build/install/example-tls /build/install/example-tls

RUN mkdir -p /tmp/sslcert

ADD tmp/sslcert /tmp/sslcert

CMD ["/bin/sh","-c","/clientScript.sh"]
