FROM openjdk:8

RUN mkdir -p /build/install/example-tls

ADD build/install/example-tls /build/install/example-tls

RUN mkdir -p /tmp/sslcert

ADD tmp/sslcert /tmp/sslcert

CMD ["/build/install/example-tls/bin/hello-world-tls-server","0.0.0.0","54440","/tmp/sslcert/server.crt","/tmp/sslcert/server.pem", "/tmp/sslcert/ca.crt"]

EXPOSE 54440

