# Source: istio/charts/nodeagent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-nodeagent-service-account
  namespace: istio-system
  labels:
    app: nodeagent
    chart: nodeagent
    heritage: Tiller
    release: istio
---
# Source: istio/charts/nodeagent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-nodeagent-istio-system
  labels:
    app: nodeagent
    chart: nodeagent
    heritage: Tiller
    release: istio
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
# Source: istio/charts/nodeagent/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-nodeagent-istio-system
  labels:
    app: nodeagent
    chart: nodeagent
    heritage: Tiller
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-nodeagent-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-nodeagent-service-account
    namespace: istio-system
---
# Source: istio/charts/nodeagent/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: istio-nodeagent
  namespace: istio-system
  labels:
    app: nodeagent
    chart: nodeagent
    release: istio
    heritage: Tiller
    istio: nodeagent
spec:
  template:
    metadata:
      labels:
        app: nodeagent
        chart: nodeagent
        release: istio
        heritage: Tiller
        istio: nodeagent
    spec:
      serviceAccountName: istio-nodeagent-service-account
      containers:
      - name: nodeagent
        image: "docker.io/istio/node-agent-k8s:1.3.1"
        imagePullPolicy: IfNotPresent
        args:
        - --log_output_level
        - debug
        volumeMounts:
        - mountPath: /var/run/sds
          name: sdsudspath
        env:
        - name: CA_ADDR
          value: "meshca.googleapis.com:443"
        - name: CA_PROVIDER
          value: "GoogleCA"
        - name: PLUGINS
          value: "GoogleTokenExchange"
        - name: "TRUST_DOMAIN"
          # Example value: "your-project-id.svc.id.goog"
          value: grpc-sds-testing.svc.id.goog
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GKE_CLUSTER_URL
          # Example value:
          # https://container.googleapis.com/v1/projects/your-project-id/locations/us-central1-c/clusters/td-sds-demo
          value: https://container.googleapis.com/v1/projects/grpc-sds-testing/locations/us-west2-a/clusters/traffic-director-cluster
      volumes:
      - name: sdsudspath
        hostPath:
          path: /var/run/sds
      #nodeSelector:
      #  -matchExpressions:
      #    -key: nodeagent-type
      #     operator: NotIn
      #     values:
      #     - pkcs8
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: nodeagent-type
                operator: NotIn
                values:
                - pkcs8
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x

---
# Source: istio/charts/nodeagent/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: istio-nodeagent-pkcs8
  namespace: istio-system
  labels:
    app: nodeagent
    chart: nodeagent
    release: istio
    heritage: Tiller
    istio: nodeagent
spec:
  template:
    metadata:
      labels:
        app: nodeagent
        chart: nodeagent
        release: istio
        heritage: Tiller
        istio: nodeagent
    spec:
      serviceAccountName: istio-nodeagent-service-account
      containers:
      - name: nodeagent-pkcs8
        image: "docker.io/jimmycyj/node-agent-k8s:0786d0"
        imagePullPolicy: IfNotPresent
        args:
        - --log_output_level
        - debug
        volumeMounts:
        - mountPath: /var/run/sds
          name: sdsudspath
        env:
        - name: CA_ADDR
          value: "meshca.googleapis.com:443"
        - name: CA_PROVIDER
          value: "GoogleCA"
        - name: PLUGINS
          value: "GoogleTokenExchange"
        - name: "TRUST_DOMAIN"
          # Example value: "your-project-id.svc.id.goog"
          value: grpc-sds-testing.svc.id.goog
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GKE_CLUSTER_URL
          # Example value:
          # https://container.googleapis.com/v1/projects/your-project-id/locations/us-central1-c/clusters/td-sds-demo
          value: https://container.googleapis.com/v1/projects/grpc-sds-testing/locations/us-west2-a/clusters/traffic-director-cluster
        - name: PKCS8_KEY
          value: "true"
      volumes:
      - name: sdsudspath
        hostPath:
          path: /var/run/sds
      nodeSelector:
        nodeagent-type: pkcs8
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
