FROM openjdk:11

ADD zatar-test/bootstrap.json /bootstrap.json

ADD zatar-test/staging-bootstrap.json /staging-bootstrap.json

ADD zatar-test/logging.properties /logging.properties

RUN mkdir -p /build/install/example-xds

ADD build/install/example-xds /build/install/example-xds

ARG builddate
ENV IMAGE_DATE=$builddate

CMD ["/bin/sleep","inf"]

EXPOSE 8000

################################################
# jove
RUN\
  apt-get update &&\
  apt-get install -y jove &&\
  apt-get clean